/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kathy' at '02-08-16 11:56' with Gradle 2.14
 *
 * @author Kathy, @date 02-08-16 11:56
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
